/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/gaming_chair.glb --transform --suspense 
Files: public/gaming_chair.glb [127.55MB] > /Volumes/Macintosh SSD/JS/chair-configurator/gaming_chair-transformed.glb [2.19MB] (98%)
Author: Allay Design (https://sketchfab.com/Alister.Dsa)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/gaming-chair-b497949336d744148f763d429b183da5
Title: Gaming Chair
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { MaterialType } from './types'

export function Model({ 
  colors = { seat: '#1a1a1a', backrest: '#1a1a1a', base: '#333333' }, 
  materialType = MaterialType.LEATHER, 
  ...props 
}) {
  const { nodes, materials } = useGLTF('/gaming_chair.glb')
  
  // Realistic material properties based on type
  const getMaterialProps = (color) => {
    const baseProps = {
      color: color,
      transparent: false,
      opacity: 1,
      side: THREE.DoubleSide,
      envMapIntensity: 1.2,
    }
    
    switch (materialType) {
      case MaterialType.LEATHER:
        return {
          ...baseProps,
          roughness: 0.35,
          metalness: 0.0,
          envMapIntensity: 0.8,
          // Leather has subtle reflection
        }
      case MaterialType.FABRIC:
        return {
          ...baseProps,
          roughness: 0.95,
          metalness: 0,
          envMapIntensity: 0.3,
          // Fabric is very matte
        }
      case MaterialType.VELVET:
        return {
          ...baseProps,
          roughness: 0.7,
          metalness: 0.0,
          envMapIntensity: 0.5,
          // Velvet has soft sheen
        }
      default:
        return {
          ...baseProps,
          roughness: 0.35,
          metalness: 0.0,
        }
    }
  }
  
  // Base/frame - realistic chrome/metal
  const baseProps = {
    roughness: 0.15,
    metalness: 0.95,
    color: colors.base,
    transparent: false,
    opacity: 1,
    side: THREE.DoubleSide,
    envMapIntensity: 2.0,
  }
  
  return (
    <group {...props} dispose={null}>
      {/* Seat */}
      <mesh 
        geometry={nodes.gaming_chair_progress_uvpolySurface238_gaming_chair_progress_uvblinn6_0.geometry}
        castShadow
        receiveShadow
      >
        <meshStandardMaterial {...getMaterialProps(colors.seat)} />
      </mesh>
      {/* Backrest */}
      <mesh 
        geometry={nodes.gaming_chair_progress_uvpolySurface238_gaming_chair_progress_uvblinn4_0.geometry}
        castShadow
        receiveShadow
      >
        <meshStandardMaterial {...getMaterialProps(colors.backrest)} />
      </mesh>
      {/* Base/Frame */}
      <mesh 
        geometry={nodes.gaming_chair_progress_uvpolySurface238_blinn1_0.geometry}
        castShadow
        receiveShadow
      >
        <meshStandardMaterial {...baseProps} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/gaming_chair.glb')
