/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/gaming_chair.glb --transform --suspense 
Files: public/gaming_chair.glb [127.55MB] > /Volumes/Macintosh SSD/JS/chair-configurator/gaming_chair-transformed.glb [2.19MB] (98%)
Author: Allay Design (https://sketchfab.com/Alister.Dsa)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/gaming-chair-b497949336d744148f763d429b183da5
Title: Gaming Chair
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gaming_chair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      {/* Подушка сидіння */}
      <mesh 
        name="Cushion"
        geometry={nodes.gaming_chair_progress_uvpolySurface238_gaming_chair_progress_uvblinn6_0.geometry} 
        material={materials.gaming_chair_progress_uvblinn6} 
      />
      
      {/* Спинка крісла */}
      <mesh 
        name="Backrest"
        geometry={nodes.gaming_chair_progress_uvpolySurface238_gaming_chair_progress_uvblinn4_0.geometry} 
        material={materials.gaming_chair_progress_uvblinn4} 
      />
      
      {/* База та колеса */}
      <mesh 
        name="Base"
        geometry={nodes.gaming_chair_progress_uvpolySurface238_blinn1_0.geometry} 
        material={materials.blinn1} 
      />
    </group>
  )
}

useGLTF.preload('/gaming_chair-transformed.glb')
